import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import BackgroundBoxes from "./components/BackgroundBoxes";
import { getCache, setCache } from "./cache";
import { client } from "./sanity";

const FOOTER_QUERY = `*[_type == "contact"][0]{
  contactAddress,
  contactPhoneNumber,
  contactEmail
}`;

async function setFooterData() {
  if (!getCache('footerData')) {
    let footerData = await client.fetch(FOOTER_QUERY);
    setCache('footerData', footerData);
  }
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  await setFooterData();

  return (
    <html lang="en">
      <body className={`${inter.className} eggshell-background`}>
        <BackgroundBoxes />
        <Navbar />
        <div className="pt-16">
          {children}
        </div>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
